Repository orionapp/orion, pull requests merged in 2018-08, with the labels that each got.

#20 Create LICENSE
  LICENSE
Labels: docs, in progress

#19 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: docs, in progress

#21 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: docs, in progress

#15 Adds welcome page
  Makefile
  assets/fonts/Source_Sans_Pro/SourceSansPro-Black.ttf
  assets/fonts/Source_Sans_Pro/SourceSansPro-BlackItalic.ttf
  assets/fonts/Source_Sans_Pro/SourceSansPro-Bold.ttf
  assets/fonts/Source_Sans_Pro/SourceSansPro-BoldItalic.ttf
  assets/fonts/Source_Sans_Pro/SourceSansPro-ExtraLight.ttf
  assets/fonts/Source_Sans_Pro/SourceSansPro-ExtraLightItalic.ttf
  assets/fonts/Source_Sans_Pro/SourceSansPro-Italic.ttf
  assets/fonts/Source_Sans_Pro/SourceSansPro-Light.ttf
  assets/fonts/Source_Sans_Pro/SourceSansPro-LightItalic.ttf
  assets/fonts/Source_Sans_Pro/SourceSansPro-Regular.ttf
  assets/fonts/Source_Sans_Pro/SourceSansPro-SemiBold.ttf
  assets/fonts/Source_Sans_Pro/SourceSansPro-SemiBoldItalic.ttf
  assets/images/favicon/favicon-1024.png
  assets/images/favicon/favicon-256.png
  assets/images/favicon/favicon.ico
  assets/images/logo/logo.png
  build.gradle
  web/build.gradle
  web/src/main/kotlin/orion/components/App.kt
  web/src/main/kotlin/orion/components/Home.kt
  web/src/main/kotlin/orion/components/Login.kt
  web/src/main/kotlin/orion/components/Logo.kt
  web/src/main/kotlin/orion/components/app/App.kt
  web/src/main/kotlin/orion/components/app/app.css
  web/src/main/kotlin/orion/components/logo/Logo.kt
  web/src/main/kotlin/orion/components/logo/logo.css
  web/src/main/kotlin/orion/css/bootstrap.css
  web/src/main/kotlin/orion/css/fonts.css
  web/src/main/kotlin/orion/css/orion.css
  web/src/main/kotlin/orion/index.kt
  web/src/main/kotlin/orion/index/fonts.css
  web/src/main/kotlin/orion/index/index.css
  web/src/main/kotlin/orion/index/index.kt
  web/src/server/server.js
  web/webpack.common.js
  web/webpack.dev.js
Labels: in progress, ui

#27 Removes sass to get Travis to build
  web/build.gradle
  web/src/main/kotlin/orion/components/Login.kt
  web/src/main/kotlin/orion/components/Logo.kt
  web/webpack.common.js
Labels: bug, in progress, web

#25 Adds PR template and Contributing guide
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: in progress
